### ISSUE TITLE
伟男 请把最近的工作传上来 我看看

### ISSUE THREAD

**Issue by zuzuligen** [neilwangweinan/classification-of-pictures#1]
伟男 请尽快把最近的工作结果传上来 我看一下 提一些意见

**Comment by zuzuligen** [comment]
另外有问题也可以在这里问 做一个记录

**Comment by neilwangweinan** [comment]
已上传。  程序Bug还未修复  这两天生病了 进展有些缓慢

**Comment by neilwangweinan** [comment]
贾老师 ，  修复了一些bug
    但是在windowsize和errorwindow的选取时仍存在问题  
 具体体现在：如果窗口选取过大 很可能涵盖多个目标   在整个程序中运行时  发现在getsamplepsf函数存在bug ：
backimg=orimg(maxposx-2_windowsize:maxposx+2_windowsize,maxposy-...
    2_windowsize:maxposy+2_windowsize);
  有的目标分割的值会越界   查询变量后发现 maxpos 和estpos 差异较大  很明显的可能是errorwindow选取时 包含了多个目标  
     目前errorwindow 和windowsize 选取是人为固定的. 35 and 5
